// <auto-generated />
namespace VidlyReborn.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Apply_Annotations_To_Customer_Name : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Apply_Annotations_To_Customer_Name));
        
        string IMigrationMetadata.Id
        {
            get { return "201812230856475_Apply_Annotations_To_Customer_Name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
