// <auto-generated />
namespace VidlyReborn.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added_Genre_id_kostil_to_Movie_Model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_Genre_id_kostil_to_Movie_Model));
        
        string IMigrationMetadata.Id
        {
            get { return "201812240721559_Added_Genre_id_kostil_to_Movie_Model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
