// <auto-generated />
namespace VidlyReborn.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added_membershipType_dto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_membershipType_dto));
        
        string IMigrationMetadata.Id
        {
            get { return "201901260847576_Added_membershipType_dto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
