// <auto-generated />
namespace VidlyReborn.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added_Driving_License_prop_to_ApplicationUser_Class : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_Driving_License_prop_to_ApplicationUser_Class));
        
        string IMigrationMetadata.Id
        {
            get { return "201901291808377_Added_Driving_License_prop_to_ApplicationUser_Class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
